### ISSUE TITLE
Regex To Format Timestamp

### ISSUE THREAD

**Issue by dalezak** [frabert/replace-string-action#1]
I'm trying to use this action to format a timestamp like `2019-11-15T1636:29.506Z` to remove the `colon` and `letters`, however it's only replacing the first instance in the string.

```
uses: frabert/replace-string-action@v1
id: format-time
with:
  pattern: '[^0-9\-]+'
  string: "2019-11-15T1636:29.506Z"
  replace-with: '-'
```

How to you do a global replace?

**Comment by dalezak** [comment]
`string = "2019-11-15T1636:29.506Z"`
> "2019-11-15T1636:29.506Z"

`replace = "-"`
> "-"

`pattern = "[^0-9]+"`
> "[^0-9]+"

`regex = new RegExp(pattern, "g")`
> /[^0-9]+/g

`string.replace(regex, replace)`
> "2019-11-15-1636-29-506-"

**Comment by frabert** [comment]
You currently can't. I'll submit a quick patch to let users specify regex flags in a minute

**Comment by frabert** [comment]
@dalezak can you try this:
```
uses: frabert/replace-string-action@master
id: format-time
with:
  pattern: '[^0-9\-]+'
  string: "2019-11-15T1636:29.506Z"
  replace-with: '-'
  flags: 'g'
```

It should work this way
