### ISSUE TITLE
not able to replace char with whitespace

### ISSUE THREAD

**Issue by einSelbst** [frabert/replace-string-action#6]
Hey! 
Thanks for the action!
I would like to replace dashes with whitespace but it seems the whitespace is ignored if given as a 'replace-with'.
I also tried passing in the unicode char `replace-with: "\u0020"` but then end up with that actual string as a replacement.

Do you think it's possible to use your action to replace something with a whitespace?
I want to generate PR titles from branch names btw.

Thanks!

**Comment by frabert** [comment]
From some preliminary testing it looks like the whitespace is being stripped from the input _before_ it gets to the action: https://github.com/frabert/replace-string-action/runs/1673088621

This makes it look like the Actions engine is doing something like `input.trim()` before forwarding the data. I'll have to check with someone else for this one...

**Comment by frabert** [comment]
I can't seem to get a reply for now, I'll leave the link here if someone wants to chime in: https://github.community/t/custom-action-whitespace-in-input-parameters-is-getting-trimmed/154470

I'm not closing this issue because it's a genuine bug, but I'm not able to propose a fix right now.

**Comment by Simran-B** [comment]
I can't find a way to preserve whitespace around action inputs, but I guess that you could add another input to let the action know that the string is JSON-encoded, do `replace-with: '" "'` in a workflow, and parse the input with `JSON.parse()` to just a space. That should preserve it. Roughly like this:

```yaml
inputs:
...
  json:
    description: Set to any value to indicate that the replace-with string is JSON-encoded
    required: true
    default: ''
```

```js
let replaceWith = core.getInput('replace-with');
const isJsonString = core.getInput('json');
if (isJsonString) {
  replaceWith = JSON.parse(replaceWith );
}
```

```yaml
uses: frabert/replace-string-action@master
with:
  pattern: '_'
  flags: 'g'
  string: '_replace_underscores_'
  replace-with: '" "'
  json: true
```
