### ISSUE TITLE
How could I get the result and use it in the next step of my workflow?

### ISSUE THREAD

**Issue by heliomar-pena** [frabert/replace-string-action#9]
I have the next workflow:

```yml
name: Chromatic Deploy Link
on: [pull_request]

jobs:
  tests:
    name: Comment Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          message: |
            Hi! :wave:
            Here's the storybook link: [Storybook deploy](https://${{ github.head_ref }}--id.chromatic.com)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I would like to replace `${{ github.head_ref }}`, which commonly is something like this `feat/branch-description`, to replace the slash `/` for a `-`, this should be the result: `feat-branch-description`, so after I modified the branch name, I want to use it at the last line, as you can see in the example

**Comment by frabert** [comment]
```
name: Chromatic Deploy Link
on: [pull_request]

jobs:
  tests:
    name: Comment Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Replace head ref
        uses: frabert/replace-string-action@v2
        id: new_head_ref
        with:
          string: '${{ github.head_ref }}'
          pattern: '/'
          replace-with: '-'
      - name: Check equality
        run: '[[ "${{ steps.test.outputs.replaced }}" == "1.0.1" ]]'
      - uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          message: |
            Hi! :wave:
            Here's the storybook link: [Storybook deploy](https://${{ steps.new_head_ref.outputs.replaced }}--id.chromatic.com)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Something like this!
